title: OpenVINO by Intel CVPR-2024
logo: https://github.com/paularamo/cvpr-2024/assets/10940214/9cfc1b86-1c4c-4f8f-a4c6-8dbc77932c2f
description: "Edge-Optimized Deep Learning: Harnessing Generative AI and Computer Vision with Open-Source Libraries."
#authors:
#  social:
#    email:    mailto:paula.ramos@intel.com
#    linkedin: https://www.linkedin.com/in/paula-ramos-41097319/
#  picture:
#    path:   /img/paula.jpg
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
