title: OpenVINO by Intel CVPR-2024
logo: https://github.com/paularamo/cvpr-2024/blob/main/img/Screenshot%202024-03-11%20115441.png
description: "Edge-Optimized Deep Learning: Harnessing Generative AI and Computer Vision with Open-Source Libraries."
#authors:
#  social:
#    email:    mailto:paula.ramos@intel.com
#    linkedin: https://www.linkedin.com/in/paula-ramos-41097319/
#  picture:
#    path:   /img/paula.jpg
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
